"""
app.py — ICAID Dashboard (Month 2 deliverable)

Run with: streamlit run app.py
(Requires `pip install streamlit plotly` — not installed in this sandbox;
run on your own machine. Layout and logic are complete and ready to go —
this file just needs `data/processed/icaid_real_panel.csv` to exist,
produced once Month 1 data collection is done. Until then it falls back
to the synthetic panel and shows a clear on-screen warning banner.)
"""
import os
from pathlib import Path
import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(page_title="ICAID Dashboard", layout="wide")

# Anchor all paths to this file's own location (not the current working
# directory). Locally, `cd src/dashboard && streamlit run app.py` sets cwd
# to src/dashboard, so "../../data/..." works. But on Streamlit Cloud, cwd
# is ALWAYS the repo root regardless of where app.py lives, so a relative
# path like "../../data/..." resolves outside the repo -> FileNotFoundError.
# Using __file__ makes this work the same way in both environments.
BASE_DIR = Path(__file__).resolve().parent
REAL_PATH = BASE_DIR / "../../data/processed/icaid_real_panel.csv"
SYNTH_PATH = BASE_DIR / "../../data/synthetic/icaid_synthetic_panel.csv"
DIMS = ["CE", "DF", "CA", "SI", "IR", "IP"]

st.title("ICAID — India-Centric AI Development Index")

if os.path.exists(REAL_PATH):
    df = pd.read_csv(REAL_PATH)
    st.success("Showing REAL, source-verified data.")
else:
    df = pd.read_csv(SYNTH_PATH)
    st.error(
        "⚠️ No real dataset found at data/processed/icaid_real_panel.csv — "
        "showing SYNTHETIC pipeline-test data only. Do NOT use these numbers "
        "in the paper. Complete Month 1 data collection first."
    )

df["ICAID_score"] = df[DIMS].mean(axis=1)

col1, col2 = st.columns([1, 2])
with col1:
    year = st.selectbox("Year", sorted(df["year"].unique()), index=len(df["year"].unique()) - 1)
    dim = st.selectbox("Dimension to map", DIMS + ["ICAID_score"])

year_df = df[df["year"] == year].sort_values(dim, ascending=False)

with col2:
    fig = px.bar(year_df, x="state", y=dim, title=f"{dim} by state — {year}")
    fig.update_layout(xaxis_tickangle=-45)
    st.plotly_chart(fig, width='stretch')

st.subheader("Ranking table")
st.dataframe(year_df[["state"] + DIMS + ["ICAID_score"]].reset_index(drop=True))

st.subheader("Trend over time")
state_pick = st.multiselect("Compare states", sorted(df["state"].unique()),
                             default=sorted(df["state"].unique())[:3])
if state_pick:
    trend_df = df[df["state"].isin(state_pick)]
    fig2 = px.line(trend_df, x="year", y="ICAID_score", color="state", markers=True)
    st.plotly_chart(fig2, width='stretch')

st.subheader("Dimension attribution (explainability)")
ATTRIBUTION_FIG_PATH = BASE_DIR / "../../results/figures/attribution_smoketest.png"
if os.path.exists(ATTRIBUTION_FIG_PATH):
    st.image(
        ATTRIBUTION_FIG_PATH,
        caption="Permutation importance — stand-in for mean |SHAP value| "
                "(SYNTHETIC smoke test, not for the paper until real SHAP "
                "is run on real data).",
        width='stretch',
    )
else:
    st.info(
        f"No attribution figure found at `{ATTRIBUTION_FIG_PATH}`. "
        "Run `python src/xai/explain.py` (or the full `run_pipeline.py`) "
        "first to generate it."
    )

st.caption(
    "Causal DAG and RL weight-convergence plots are generated by "
    "src/causal_discovery and src/rl_weighting respectively — wire their "
    "outputs into this dashboard once real data is in place."
)
